### ISSUE TITLE
Document Import/Export in the uP5 Manual

### ISSUE THREAD

**Issue by drewwills** [uPortal-Project/uPortal#1241]
Import/Export is an immensely important tool for working with uPortal.  Previous versions of the Manual (in Confluence) had documentation for using it, but the new (markdown-based) Manual doesn't appear to have any.

The [previous documentation is here](https://wiki.jasig.org/display/UPM42/Importing+and+Exporting+data), but the commands have changed, and it can't be copied forward (to uP5) verbatim.

**Comment by 555vedant** [comment]
where i can find the UP5 Manul ??

**Comment by 555vedant** [comment]
from where i can find the commands for import/export ??
