### ISSUE TITLE
Implement an example config to disable JGroups 

### ISSUE THREAD

**Issue by cbeach47** [uPortal-Project/uPortal#1739]
Adopters would like to disable JGroups with minimal effort.  

The plan is to create an example file alongside `/uPortal-webapp/src/main/resources/properties/jgroups.xml` (`jgroups.xml.disable`) that will turn off all JGroups features in uPortal, and then another ticket in uPortal-start with documentation on how use that file to disable JGroups.

**Comment by bjagg** [comment]
[ehcache-no-jgroups.txt](https://github.com/Jasig/uPortal/files/3895083/ehcache-no-jgroups.txt)

**Comment by bjagg** [comment]
used vim with command: `g/JGroupsCacheReplicatorFactory/-1,+4d`

**Comment by bjagg** [comment]
This file should be renamed with `.xml` suffix and added to uPortal in the same directory as `ehcache.xml`.

**Comment by bjagg** [comment]
fix: make jgroups optional to avoid network delays
