### ISSUE TITLE
docs: Migrate docs about merging attribute sources from Confluence

### ISSUE THREAD

**Issue by jonathanmtran** [uPortal-Project/uPortal#2287]
The instructions for User Attributes [1] is missing the bit about configuring a `CachingPersonAttributeDaoImpl` bean to merge the attribute source(s). The documentation in Confluence [2] about this should be migrated into this (or the appropriate) repo.

[1] https://github.com/uPortal-Project/uPortal/blob/HEAD/docs/implement/user-attributes/README.md
[2]  https://apereo.atlassian.net/wiki/spaces/UPM43/pages/103948916/JDBC+User+Attribute+Sources

**Additional context**
This came to light via https://groups.google.com/a/apereo.org/g/uportal-user/c/boXVnfKEZAw/m/tQiqv19nAQAJ

**Comment by 555vedant** [comment]
can you assign this to me

**Comment by ChristianMurphy** [comment]
Welcome @555vedant! Sure you are welcome to tackle migrating these docs

**Comment by 555vedant** [comment]
PR #2857
